<template>
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <img src="static/Logomakr_5G0cO7.png">
      <h1>test</h1>
      <router-link to="/" class="navbar-brand"> Servidces</router-link>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <button class="btn btn-danger log" @click="handleLogout()">Log out </button>
        <button class="btn btn-info log" @click="handleLogin()">Log In</button>
      </li>
    </ul>
  </nav>
</template>

<script>
// import { isLoggedIn, login, logout } from '../../utils/auth';

export default {
  name: 'app-nav',
  methods: {
    // handleLogin() {
    //   login();
    // },
    // handleLogout() {
    //   logout();
    // },
    // isLoggedIn() {
    //   return isLoggedIn();
    // },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.navbar-right { margin-right: 0px !important}

.log {
  margin: 5px 10px 0 0;
}
</style>
